"""initial_schema

Revision ID: 94a9343811fc
Revises: 
Create Date: 2026-03-10 23:45:27.964131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a9343811fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_db_id', sa.String(), nullable=False),
    sa.Column('backup_type', sa.Enum('AUTOMATED', 'MANUAL', 'PRE_MIGRATION', 'SNAPSHOT', name='backuptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'EXPIRED', name='backupstatus'), nullable=True),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('rds_snapshot_id', sa.String(), nullable=True),
    sa.Column('rds_snapshot_arn', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_tenant_db_id'), 'backups', ['tenant_db_id'], unique=False)
    op.create_table('migrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('up_sql', sa.Text(), nullable=False),
    sa.Column('down_sql', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_databases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('db_identifier', sa.String(), nullable=True),
    sa.Column('db_host', sa.String(), nullable=True),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(), nullable=False),
    sa.Column('db_username', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='databasetier'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'MIGRATING', 'BACKING_UP', 'SCALING', 'ERROR', 'DEPROVISIONED', name='databasestatus'), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('aws_region', sa.String(), nullable=True),
    sa.Column('rds_arn', sa.String(), nullable=True),
    sa.Column('terraform_workspace', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('migrations_applied', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_cost_estimate', sa.Float(), nullable=True),
    sa.Column('multi_az', sa.Boolean(), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_enabled', sa.Boolean(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_identifier')
    )
    op.create_index(op.f('ix_tenant_databases_tenant_id'), 'tenant_databases', ['tenant_id'], unique=False)
    op.create_table('bulk_migration_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('migration_id', sa.String(), nullable=True),
    sa.Column('target_env', sa.String(), nullable=True),
    sa.Column('target_tenant_ids', sa.JSON(), nullable=True),
    sa.Column('total_databases', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='migrationstatus'), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('migration_id', sa.String(), nullable=True),
    sa.Column('tenant_db_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='migrationstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.ForeignKeyConstraint(['tenant_db_id'], ['tenant_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_runs')
    op.drop_table('bulk_migration_jobs')
    op.drop_index(op.f('ix_tenant_databases_tenant_id'), table_name='tenant_databases')
    op.drop_table('tenant_databases')
    op.drop_table('migrations')
    op.drop_index(op.f('ix_backups_tenant_db_id'), table_name='backups')
    op.drop_table('backups')
    # ### end Alembic commands ###
